### ISSUE TITLE
No network information is not shown in list of exams

### ISSUE THREAD

**Issue by bharathwaaj** [testpress/android#5]
When network is disconnected, it shows no exams in the list of exams instead of showing network unavailable.

**Steps**
1. Connect to internet
2. Login successfully and go to list of available exams
3. Disconnect internet
4. Refresh the list of available exams

**Expected**
Should show "No active internet connection" message in the list view

**Observed**
Shows "No Exams" message

**Comment by bharathwaaj** [comment]
04-25 11:34:20.402    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ ---> HTTP GET https://demo.testpress.in/api/v2.1/exams/available/
04-25 11:34:20.402    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RwcmVzcyIsInVzZXJfaWQiOjE3LCJlbWFpbCI6InN1cHBvcnRAdGVzdHByZXNzLmluIiwiZXhwIjoxNDI5ODYwODk1fQ.MANw107r1c-xlZoFvIR6_qTmLdwWW3jw3-0MMXNEPWE
04-25 11:34:20.403    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ User-Agent: testpress/1.0 (Android 5.0.2; Motorola Falcon_umtsds / Motorola XT1033; Airtel)[preload=false;locale=en_GB;clientidbase=android-motorola]
04-25 11:34:20.403    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ Content-Type: application/json
04-25 11:34:20.403    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ ---> END HTTP (no body)
04-25 11:34:20.457    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ ---- ERROR https://demo.testpress.in/api/v2.1/exams/available/
04-25 11:34:20.471    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ java.net.UnknownHostException: Unable to resolve host "demo.testpress.in": No address associated with hostname
            at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
            at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getExams(Unknown Source)
            at in.testpress.testpress.core.TestpressService.getExams(TestpressService.java:50)
            at in.testpress.testpress.core.ExamPager.getItems(ExamPager.java:62)
            at in.testpress.testpress.core.ResourcePager.next(ResourcePager.java:103)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:73)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:69)
            at in.testpress.testpress.ui.ThrowableLoader.loadInBackground(ThrowableLoader.java:36)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
            at libcore.io.Posix.android_getaddrinfo(Native Method)
            at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
            at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getExams(Unknown Source)
            at in.testpress.testpress.core.TestpressService.getExams(TestpressService.java:50)
            at in.testpress.testpress.core.ExamPager.getItems(ExamPager.java:62)
            at in.testpress.testpress.core.ResourcePager.next(ResourcePager.java:103)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:73)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:69)
            at in.testpress.testpress.ui.ThrowableLoader.loadInBackground(ThrowableLoader.java:36)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
04-25 11:34:20.471    6853-7653/in.testpress.testpress.debug D/Retrofit﹕ ---- END ERROR
04-25 11:38:16.108    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ ---> HTTP GET https://demo.testpress.in/api/v2.1/exams/available/
04-25 11:38:16.108    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RwcmVzcyIsInVzZXJfaWQiOjE3LCJlbWFpbCI6InN1cHBvcnRAdGVzdHByZXNzLmluIiwiZXhwIjoxNDI5ODYwODk1fQ.MANw107r1c-xlZoFvIR6_qTmLdwWW3jw3-0MMXNEPWE
04-25 11:38:16.108    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ User-Agent: testpress/1.0 (Android 5.0.2; Motorola Falcon_umtsds / Motorola XT1033; Airtel)[preload=false;locale=en_GB;clientidbase=android-motorola]
04-25 11:38:16.108    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ Content-Type: application/json
04-25 11:38:16.108    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ ---> END HTTP (no body)
04-25 11:38:16.110    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ ---> HTTP GET https://demo.testpress.in/api/v2.1/exams/upcoming/
04-25 11:38:16.110    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RwcmVzcyIsInVzZXJfaWQiOjE3LCJlbWFpbCI6InN1cHBvcnRAdGVzdHByZXNzLmluIiwiZXhwIjoxNDI5ODYwODk1fQ.MANw107r1c-xlZoFvIR6_qTmLdwWW3jw3-0MMXNEPWE
04-25 11:38:16.110    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ User-Agent: testpress/1.0 (Android 5.0.2; Motorola Falcon_umtsds / Motorola XT1033; Airtel)[preload=false;locale=en_GB;clientidbase=android-motorola]
04-25 11:38:16.110    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ Content-Type: application/json
04-25 11:38:16.110    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ ---> END HTTP (no body)
04-25 11:38:16.135    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ ---- ERROR https://demo.testpress.in/api/v2.1/exams/upcoming/
04-25 11:38:16.139    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ ---- ERROR https://demo.testpress.in/api/v2.1/exams/available/
04-25 11:38:16.168    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ java.net.UnknownHostException: Unable to resolve host "demo.testpress.in": No address associated with hostname
            at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
            at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getExams(Unknown Source)
            at in.testpress.testpress.core.TestpressService.getExams(TestpressService.java:50)
            at in.testpress.testpress.core.ExamPager.getItems(ExamPager.java:62)
            at in.testpress.testpress.core.ResourcePager.next(ResourcePager.java:103)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:73)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:69)
            at in.testpress.testpress.ui.ThrowableLoader.loadInBackground(ThrowableLoader.java:36)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
            at libcore.io.Posix.android_getaddrinfo(Native Method)
            at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
            at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getExams(Unknown Source)
            at in.testpress.testpress.core.TestpressService.getExams(TestpressService.java:50)
            at in.testpress.testpress.core.ExamPager.getItems(ExamPager.java:62)
            at in.testpress.testpress.core.ResourcePager.next(ResourcePager.java:103)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:73)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:69)
            at in.testpress.testpress.ui.ThrowableLoader.loadInBackground(ThrowableLoader.java:36)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
04-25 11:38:16.168    6853-9720/in.testpress.testpress.debug D/Retrofit﹕ ---- END ERROR
04-25 11:38:16.175    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ java.net.UnknownHostException: Unable to resolve host "demo.testpress.in": No address associated with hostname
            at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
            at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getExams(Unknown Source)
            at in.testpress.testpress.core.TestpressService.getExams(TestpressService.java:50)
            at in.testpress.testpress.core.ExamPager.getItems(ExamPager.java:62)
            at in.testpress.testpress.core.ResourcePager.next(ResourcePager.java:103)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:73)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:69)
            at in.testpress.testpress.ui.ThrowableLoader.loadInBackground(ThrowableLoader.java:36)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
            at libcore.io.Posix.android_getaddrinfo(Native Method)
            at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
            at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getExams(Unknown Source)
            at in.testpress.testpress.core.TestpressService.getExams(TestpressService.java:50)
            at in.testpress.testpress.core.ExamPager.getItems(ExamPager.java:62)
            at in.testpress.testpress.core.ResourcePager.next(ResourcePager.java:103)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:73)
            at in.testpress.testpress.ui.PagedItemFragment$1.loadData(PagedItemFragment.java:69)
            at in.testpress.testpress.ui.ThrowableLoader.loadInBackground(ThrowableLoader.java:36)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
04-25 11:38:16.184    6853-9719/in.testpress.testpress.debug D/Retrofit﹕ ---- END ERROR
